### ISSUE TITLE
CaPTK

### ISSUE THREAD

**Issue by carriewright11** [jhudsl/ITN_computing_resources#23]
https://www.med.upenn.edu/cbica/captk/

Spryidon Bakas can help provide information

**Comment by carriewright11** [comment]
CaPTk beyond being a stand-alone software client it also makes its computational functionality on image analytics available for free, through the Image Processing Portal (IPP) that offers compute power through the CaPTk's supporting high performance computing cluster.

**Comment by kweav** [comment]
CaPTk was added Jan 2023 with commit c6cdffb
